---
title: "TidyTuesday 2021 Week 6: HBCU Enrolment"
description: |
  A short description of the post.
author:
  - name: Kyle Belanger
    url: {}
date: 02-03-2021
categories:
  - TidyTuesday
output:
  distill::distill_article:
    self_contained: false
    toc: TRUE
    code_folding: TRUE
draft: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# Introduction



# Load Data

Note use of import from %nin% 

```{r}
library(dplyr)
import::from(Hmisc, `%nin%`)

hs_students_raw <- readxl::read_xlsx("104.10.xlsx", sheet = 1)

glimpse(hs_students_raw)

```

filter year 1985 and up
remove weird dates

```{r}



hs_students <- hs_students_raw %>% 
  filter(Total >= 1985) %>% 
  filter(Total %nin% c(19103, 19203, 19303))

```

convert to numeric

```{r}
hs_students <- hs_students_raw %>% 
  filter(Total >= 1985) %>% 
  filter(Total %nin% c(19103, 19203, 19303)) %>% 
  mutate(across(everything(), as.numeric))
  
```

rename columns 

```{r}

hs_students <- hs_students_raw %>% 
  filter(Total >= 1985) %>% 
  filter(Total %nin% c(19103, 19203, 19303)) %>% 
  mutate(across(everything(), as.numeric)) %>% 
  rename(year = Total) %>% 
  rename_with(
    ~stringr::str_remove_all(
      .
      ,", percent of all persons age 25 and over|1"
      )
    )
  

```

reomve asain/pac total as they are stored in seperate columns 
reomve string asian/pac

```{r}

hs_students <- hs_students_raw %>% 
  filter(Total >= 1985) %>% 
  filter(Total %nin% c(19103, 19203, 19303)) %>% 
  mutate(across(everything(), as.numeric)) %>% 
  rename(year = Total) %>% 
  rename_with(
    ~stringr::str_remove_all(
      .
      ,", percent of all persons age 25 and over|1"
      )
    ) %>% 
  select(-contains("Total - Asian/Pacific Islander")) %>% 
  rename_with(
    ~stringr::str_remove_all(
      .
      ,"Asian/Pacific Islander - "
    )
  )

```

pivot data

```{r}
hs_students_long <- hs_students %>% 
  tidyr::pivot_longer(-year)
```


